name: Deploy on Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync project
        run: |
          rsync -a --delete \
          --exclude ".git" \
          --exclude "node_modules" \
          ./ /home/michalx106/srv/RaspberryPiServer2/

      - name: Build backend and frontend
        run: |
          cd /home/michalx106/srv
          docker compose build api frontend

      - name: Restart only backend and frontend
        run: |
          cd /home/michalx106/srv
          docker compose up -d api frontend

      - name: Show running containers
        run: |
          cd /home/michalx106/srv
          docker compose ps
