name: Deploy on Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Sync repo
        run: |
          rsync -a --delete \
            --exclude ".git" \
            --exclude "node_modules" \
            ./ /home/michalx106/srv/RaspberryPiServer2/

      - name: Build only backend and frontend
        run: |
          cd /home/michalx106/srv/RaspberryPiServer2
          docker compose build backend frontend

      - name: Restart only backend and frontend
        run: |
          cd /home/michalx106/srv/RaspberryPiServer2
          docker compose up -d backend frontend

      - name: Show status
        run: |
          cd /home/michalx106/srv/RaspberryPiServer2
          docker compose ps
